image: condaforge/mambaforge:latest

stages:          # List of stages for jobs, and their order of execution
  - test

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - apt-get --allow-releaseinfo-change update -y
    - apt-get -y upgrade
    - apt-get install -y libgomp1
    - apt-get install -y libgl1-mesa-glx
    - mamba env create -f environment.yml --prefix /autocnet
    - /autocnet/bin/pytest .

