image: code.usgs.gov:5001/astrogeology/autocnet/mambaforge

services:
    - name: code.usgs.gov:5001/astrogeology/autocnet/postgis
      alias: postgres
      entrypoint: ["docker-entrypoint.sh"]
      command: ["postgres"]

variables:
    POSTGRES_HOST: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: NotTheDefault
    POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - test
unit-test-job:
  stage: test
  script:
    - mamba env create -f environment.yml -n autocnet_env
    - conda init
    - source /root/.bashrc
    - source activate autocnet_env
    - psql -h $POSTGRES_HOST -c 'create database template_postgis;' -U postgres ;
    - psql template_postgis -h $POSTGRES_HOST -U postgres -c 'create extension postgis';
    - psql template_postgis -U $POSTGRES_USER -h $POSTGRES_HOST -c 'create extension postgis_topology';
    - psql -d template_postgis -U $POSTGRES_USER -h $POSTGRES_HOST -c 'GRANT ALL ON geometry_columns TO PUBLIC;';
    - psql -d template_postgis -U $POSTGRES_USER -h $POSTGRES_HOST -c 'GRANT ALL ON geography_columns TO PUBLIC;';
    - psql -d template_postgis -U $POSTGRES_USER -h $POSTGRES_HOST -c 'GRANT ALL ON spatial_ref_sys TO PUBLIC;';
    - ls /usr/lib/x86_64-linux-gnu/
    - pytest .
