image: condaforge/mambaforge:latest

services:
    - name: code.usgs.gov:5001/astrogeology/autocnet/postgres
      alias: postgres
      entrypoint: ["docker-entrypoint.sh"]
      command: ["postgres"]

variables:
    POSTGRES_HOST: localhost
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: NotTheDefault
    POSTGRES_PORT: 35432
    POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - test
unit-test-job: 
  stage: test
  script:
    - apt-get --allow-releaseinfo-change update -y
    - apt-get -y upgrade
    - apt-get install -y libgomp1
    - apt-get install -y libgl1-mesa-glx
    - mamba env create -f environment.yml -n autocnet_env
    - conda init
    - source /root/.bashrc
    - source activate autocnet_env
    - psql -h $POSTGRES_HOST -c 'create database template_postgis;' -U postgres -p 35432;
    - psql template_postgis -h $POSTGRES_HOST -U postgres -p 35432 -c 'create extension postgis';
    - psql template_postgis -U $POSTGRES_USER -h $POSTGRES_HOST -p 35432 -c 'create extension postgis_topology';
    - psql -d template_postgis -U $POSTGRES_USER -h $POSTGRES_HOST -p 35432 -c 'GRANT ALL ON geometry_columns TO PUBLIC;';
    - psql -d template_postgis -U $POSTGRES_USER -h $POSTGRES_HOST -p 35432 -c 'GRANT ALL ON geography_columns TO PUBLIC;';
    - psql -d template_postgis -U $POSTGRES_USER -h $POSTGRES_HOST -p 35432 -c 'GRANT ALL ON spatial_ref_sys TO PUBLIC;';
    - /autocnet/bin/pytest .