image: code.usgs.gov:5001/astrogeology/autocnet/mambaforge

services:
    - name: code.usgs.gov:5001/astrogeology/autocnet/postgis
      alias: postgres
      entrypoint: ["docker-entrypoint.sh"]
      command: ["postgres"]

variables:
    POSTGRES_HOST: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: NotTheDefault
    POSTGRES_HOST_AUTH_METHOD: trust

before_script:
  - mamba env create -f environment.yml -n autocnet_env
  - conda init
  - source /root/.bashrc
  - source activate autocnet_env
  - mamba install pip

stages:
  - test
  - deploy

pages:
  stage: deploy 
  script:
    - mamba install --file doc_requirements.txt
    - sphinx-build -b html docs public
  artifacts:
    paths:
      - public
