sudo: true

branches:
  only:
    - dev
    - testing

os:
  - linux
  - osx

env:
  global:
    - PGPORT=5433
  matrix:
    - PYTHON_VERSION=3.5
    - PYTHON_VERSION=3.6
    - PYTHON_VERSION=3.7

# Setup a postgresql instance w/postgis
services:
  - postgresql
addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
      - postgresql-client-10
  
before_install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      curl -o miniconda.sh  https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Create the env
  - conda create -q -n test python=$PYTHON_VERSION
  - source activate test

  # Install dependencies
  - conda env update -n test -f environment.yml
  - export PROJ_LIB=$CONDA_PREFIX/share/proj  

  # Setup the database user
  - sudo -u postgres psql -c "CREATE USER testuser WITH PASSWORD 'password'"
  - sudo -u postgres psql -c "ALTER ROLE testuser SUPERUSER"

  # Setup autocnet to connect to the db
  - export autocnet_config=sample.yml

before_script:
  # Create the database
  - PGPASSWORD=password psql -U testuser -c "create database travis_ci_test;"
  - PGPASSWORD=password psql -U testuser -d travis_ci_test -c "CREATE EXTENSION postgis;"

script:
  - pytest autocnet tests

after_success:
  - coveralls
  # Need to do the build in the root
  - source deactivate
  - conda install conda-build anaconda-client
  - conda config --set anaconda_upload yes
  - conda build --token $CONDA_UPLOAD_TOKEN --python $PYTHON_VERSION -c conda-forge -c menpo -c usgs-astrogeology conda

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6cbe4b65fff6764ed80f
    on_success: always
    on_failure: always
