channels:
  - conda-forge

dependencies:
  - python>=3.10
  - csmapi
  - cython
  - cyvlfeat
  - matplotlib
  - dill
  - conda-forge::gdal
  - geoalchemy2
  - geopandas
  - hoggorm
  - imageio
  - ipykernel
  - kalasiris
  - conda-forge::knoten
  - networkx>=2,<3
  - numpy
  - libopencv
  - opencv
  - py-opencv
  - conda-forge::plio>=1.5.4
  - pandas
  - pyyaml
  - plurmy
  - psycopg2
  - pvl>=1.0,<2
  - proj
  - conda-forge::pyproj 
  - richdem
  - scikit-image>=0.17
  - scikit-learn
  - scipy
  - shapely
  - sqlalchemy
  - sqlalchemy-utils
  - redis-py<5
  - conda-forge::usgscsm
  - vlfeat
  - protobuf
