channels:
  - conda-forge

dependencies:
  - python>=3
  - coveralls
  - csmapi
  - cython
  - cyvlfeat
  - matplotlib
  - dill
  - gdal
  - fakeredis
  - geoalchemy2
  - geopandas
  - gdal
  - hiredis
  - hoggorm
  - imageio
  - ipykernel
  - jupyter
  - kalasiris
  - conda-forge::knoten
  - ncurses
  - networkx>=2,<3
  - numpy
  - opencv <= 3.5
  - pillow
  - plio>=1.3
  - pandas
  - pyyaml
  - plurmy
  - psycopg2
  - pvl>=1.0,<2
  - proj=7.0.0
  - pvl = 1.0
  - pyproj
  - pytest
  - pytest-cov
  - pytest-mock
  - runipy
  - richdem
  - scikit-image>=0.17
  - scikit-learn
  - scipy=1.2.1
  - shapely
  - sqlalchemy
  - sqlalchemy-utils
  - redis-py
  - conda-forge::usgscsm>=1.6.0
  - vlfeat
  - pip
  - protobuf
  - pysal
