channels:
  - conda-forge
  - usgs-astrogeology

dependencies:
  - python>=3
  - csmapi
  - cython
  - cyvlfeat
  - matplotlib
  - dill
  - conda-forge::gdal
  - geoalchemy2
  - geopandas
  - hoggorm
  - imageio
  - ipykernel
  - kalasiris
  - knoten=0.2.0
  - ncurses
  - networkx=2
  - numpy
  - opencv <= 3.5
  - plio>=1.3
  - pandas
  - pyyaml
  - plurmy
  - psycopg2
  - pvl=1.0
  - proj=7.0.0
  - conda-forge::pyproj 
  - richdem
  - scikit-image=0.17
  - scikit-learn
  - scipy=1.2.1
  - shapely
  - sqlalchemy=1.4
  - sqlalchemy-utils=0.37.0
  - redis-py
  - usgscsm
  - vlfeat
  - pip
  - protobuf
