package:
  name: autocnet
  version: 1.2.1
  
channels:
  - conda-forge
  
source:
   git_url: https://code.usgs.gov/astrogeology/autocnet
   git_rev: main

requirements:
    build:
      - csmapi
      - dill
      - geoalchemy2
      - geopandas
      - kalasiris
      - knoten
      - networkx
      - opencv
      - plio
      - plurmy
      - pyyaml
      - redis-py
      - scikit-image
      - scipy
      - shapely
      - sqlalchemy-utils
    host:
      - python>=3.10
    run:
      - python>=3.10
      - csmapi
      - cython
      - cyvlfeat
      - matplotlib
      - dill
      - conda-forge::gdal
      - geoalchemy2
      - geopandas
      - hoggorm
      - imageio
      - ipykernel
      - kalasiris
      - conda-forge::knoten
      - networkx>=2,<3
      - numpy
      - opencv
      - conda-forge::plio>=1.3
      - pandas
      - pyyaml
      - plio>=1.5.4
      - plurmy
      - psycopg2
      - pvl>=1.0,<2
      - proj
      - conda-forge::pyproj 
      - richdem
      - scikit-image>=0.17
      - scikit-learn
      - scipy
      - shapely
      - sqlalchemy
      - sqlalchemy-utils
      - redis-py<5
      - conda-forge::usgscsm>=2.0.0
      - vlfeat
      - protobuf
      - pip
      - pip:
        - image_registration

test:
  imports:
    - autocnet
    - autocnet.graph.network
